### ISSUE TITLE
Using a block adds an empty `tag` to the stack it came from

### ISSUE THREAD

**Issue by Zeklandia** [BradBot1/BradsFabricApi#3]
If you use, place, or drop an item from a stack of blocks, the whole stack will be given an empty `tag` field. This causes the stacks not to mix or sort correctly.
![image](https://user-images.githubusercontent.com/2998257/136641272-88a2e562-96e9-4049-bdea-f74dedf995f8.png)

**Comment by BradBot1** [comment]
What version are you on?

**Comment by Zeklandia** [comment]
BFAPI 1.1.9, Fabric 1.17.1.

**Comment by kutaxoff** [comment]
Unfortunately, the issue still persists on Fabric 1.18.1, BFAPI 1.3.0

**Comment by BradBot1** [comment]
I am quite unsure on how this would persist as the synthetic library is no longer present in BFAPI. I will look into this but can I please have you full mod list?

**Comment by BradBot1** [comment]
I just ran a test and I am not reproducing what you say, if you are sure that it is BFAPI please open a new issue for me.
