### ISSUE TITLE
BFAPI mixin fails to apply, causes network stack crash

### ISSUE THREAD

**Issue by Zeklandia** [BradBot1/BradsFabricApi#4]
BFAPI 1.1.10, Fabric 1.17.1.

[latest.log](https://github.com/BradBot1/BradsFabricApi/files/7434177/latest.log)

**Comment by Zeklandia** [comment]
I was able to reproduce the issue by testing each mod one at a time. The conflict is with Ledger (1.1.1).

**Comment by BradBot1** [comment]
Thanks ill look into it

**Comment by BradBot1** [comment]
I have resolved the issue with compatibility, please update to the newest version. Thanks for the issue <3

**Comment by BradBot1** [comment]
And if this issue persists for some reason feel free to reopen this issue
