### ISSUE TITLE
server crashes on startup with just BFAPI and Fabric API installed

### ISSUE THREAD

**Issue by charcoalpeas** [BradBot1/BradsFabricApi#6]
with just BFAPI installed, the server starts fine with the following error message
`[10:09:44] [main/ERROR]: Adding duplicate key 'ResourceKey[bfapi:events / minecraft:command_registration]' to registry`

with BFAPI and Fabric API installed, it fails to start
[latest.log](https://github.com/BradBot1/BradsFabricApi/files/7691920/latest.log)

bfapi 1.2.0 and fabric api 0.44.0+1.18

**Comment by Khikki** [comment]
Exactly the same problem.

**Comment by BradBot1** [comment]
Just tested it, I got the same result. Thanks for the report and I'll be straight on it

**Comment by BradBot1** [comment]
My bad, this is the dumbest issue ever. I literally double registered, the patch will be out soon ;/ (under v1.2.1)

**Comment by BradBot1** [comment]
now imma fix mods that depend on it since i renamed an important method 🤦

**Comment by BradBot1** [comment]
Done, feel free to get the latest version of the mods <3
