### ISSUE TITLE
Items not stacking on fabric server

### ISSUE THREAD

**Issue by zoharTRP** [BradBot1/BradsFabricApi#7]
I run a fabric Minecraft server for me and some friends, when I started the server for the thirst time it had several server-side mods along with bfapi for fabricsit. As soon as we broke some blocks we noticed some weird behavior with items stacking. What was happening is that if you broke blocks in everything would be fine but if at any point you used the stack of the blocks you were mining/obtaining and then continuing to get more it would create a different stack. As soon as I removed bfapi the issue got fixed.

Problem demonstrated below:

https://user-images.githubusercontent.com/51754609/152683640-b2d51c7d-4ea9-44d0-9324-88dd3b86a159.mp4

**Comment by BradBot1** [comment]
Thanks for the report, I'll begin trying to reproduce now <3

**Comment by BradBot1** [comment]
I have discovered what I believe to be the problem (shockingly it isn't SlotMixin). When an ItemStack is 'used' (clicked on a block etc) BFAPI will check for a mark, but while doing so it will use 'getOrCreateNbt' meaning the stack will become unstackable with unused items.

I have patched this out in 1.3.1, please update as soon as you can and thank you for the report with a video <3

**Comment by zoharTRP** [comment]
No problem, honestly annoyed the hell out of me and my friends so I was like let's actually make the problem easy to understand with a video. Personally, I am always annoyed when people don't have a video. 
Thank you for updating asap xx
