### ISSUE TITLE
Starting server with Aternos, it will not load BFAPI due to a issue?

### ISSUE THREAD

**Issue by AprilLaMay** [BradBot1/BradsFabricApi#9]
bfapi.jar
165.68 kB
fabric-api-0.48.0+1.18.2.jar
1.24 MB
FabricSit-1.7.1.jar
17.02 kB
iris-mc1.18.2-1.2.2-build.32.jar
1.43 MB
lithium-fabric-mc1.18.2-0.7.9.jar
433.30 kB
phosphor-fabric-mc1.18.x-0.8.1.jar
87.91 kB
voicechat-fabric-1.18.2-2.2.31.jar
5.31 MB
worldedit-mod-7.2.10.jar

Here was the last log that happened as I was trying to do the server start.
[Server Error.txt](https://github.com/BradBot1/BradsFabricApi/files/8385825/Server.Error.txt)

**Comment by BradBot1** [comment]
1.18.2 is not currently supported, I am working on a patch rn but I am a little tight on time so expect it in about a week
